### ISSUE TITLE
User-installed themes not found

### ISSUE THREAD

**Issue by salim-b** [flathub/org.geany.Geany#10]
If I'm not mistaken, I have to put [Geany themes](https://www.geany.org/download/themes/) for the Flatpak version to `~/.var/app/org.geany.Geany/config/colorschemes/` instead of `~/.config/geany/colorschemes/`, right?

But when I do, they aren't found. I did

```sh
mkdir -p "${HOME}/.var/app/org.geany.Geany/config/colorschemes"
wget --directory-prefix="${HOME}/.var/app/org.geany.Geany/config/colorschemes" https://raw.github.com/geany/geany-themes/master/colorschemes/sleepy-pastel.conf
```

but after a restart of Geany, the theme still doesn't appear in the theme dialog.

I'm on Ubuntu 20.04 and installed Flatpak from [this PPA](https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak) (currently Flatpak 1.6.3) if that matters.

**Comment by TingPing** [comment]
Just the wrong dir, you meant: `~/.var/app/org.geany.Geany/config/geany/colorschemes/`

**Comment by salim-b** [comment]
Ahhh, stupid me! Thanks a lot!
