### ISSUE TITLE
Verify the Flatpak

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.geany.Geany#103]
If possible, please consider verifying this Flatpak.

Here is more info about verified apps: https://flathub.org/about

**Comment by TiZ-HugLife** [comment]
That's impossible. Geany's developers have no interest in maintaining the Flatpak manifests. So it's either unverified, or it doesn't exist. That's all there is to it.

I hope you're not just going around to every unverified project you find and opening issues like this.

**Comment by AsciiWolf** [comment]
Fair points and do not worry, I am not going around every unverified project, just some (many of my Flatpaks are also still unverified). However, unverified Flatpaks will probably die in the future - for a good reason. Linux Mint already nuked them (they won't be displayed anymore in their Software Manager app) and other distributions will probably follow. As far as I know, there were also some plans to do not allow unverified apps on Flathub at all, but these plans were postponed.
