### ISSUE TITLE
How to spawn host terminal?

### ISSUE THREAD

**Issue by ttoommxx** [flathub/org.geany.Geany#108]
How do I spawn the host terminal from within Geany so that I can use my host applications from terminal and not the sandboxed ones?

**Comment by ttoommxx** [comment]
Just noticed that I did not change the permission on Flatseal, need to add Dbus support there and then flatpak-spawn will work as expected. Will add instructions to the readme file

**Comment by TiZ-HugLife** [comment]
Submit a pull request for README.md (which was only recently created) and I'll happily merge it.
