### ISSUE TITLE
Seems to be GTK+ 2 still

### ISSUE THREAD

**Issue by kurobeats** [flathub/org.geany.Geany#3]
Is it intentional that this build is not using the newer GTK3 interface?

**Comment by TingPing** [comment]
Well once upstream makes a stable release with GTK3 being not experimental the package will follow.

**Comment by b4n** [comment]
@TingPing GTK3 support is considered non-experimental in Geany since version 1.25: *GTK3 support, while not enabled by default, is now considered stable.*
We apparently failed to update the *configure* help to reflect that though, I'll fix it.
