### ISSUE TITLE
Copying to clipboard broken on Wayland

### ISSUE THREAD

**Issue by jntesteves** [flathub/org.geany.Geany#42]
Since Geany started defaulting to Wayland a few months back, copying to clipboard has been broken. Copy/paste within Geany works, and pasting to other Xorg apps also work. But pasting to other Wayland apps does not work. In fact, when copying text from Geany, the Wayland clipboard is emptied.

Removing the Wayland permission to force use Xorg "solves" the problem.

I'm not sure if the problem is specific to Flatpak or something that changed on upstream, so I'm reporting here first. Reverting the Flatpak to use Xorg by default would solve the issue, but I don't think it's worth doing just to solve this somewhat minor annoyance.

**Comment by HugLifeTiZ** [comment]
I use Plasma on Xorg, so I can only guess what's up; a cursory search shows two upstream bugs: [this one](https://github.com/geany/geany/issues/2629) that claims it's related to Scintilla, and [this upstream bug](https://github.com/geany/geany/issues/3345) which claims that a GTK3 patch fixed it.

I'm glad there's an easy enough workaround; this could be done in Flatseal for anyone stumbling on this. As for whether or not I'll remove that permission in this package, I don't know yet; It seems like the bug may be inconsistent on which environments it happens in, so I'd need to hear that multiple folks are experiencing the problem across a multitude of DEs before making the change here. Which DE are you using?

**Comment by jntesteves** [comment]
I use Gnome. I think I started seeing the issue sometime during Fedora 36 lifetime, and it persisted after updating to 37. So Gnome 42 and 43 for me.

Thanks for taking the time to investigate this. I seem to have the exact same issue as geany/geany#3345, so hopefully it should be fixed when the runtime updates GTK to version 3.24.36, which, if all goes well, will be merged today: [https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/11310](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/11310). Then it usually takes some weeks before someone tags a release of it.

**Comment by jntesteves** [comment]
Closing as the issue is fixed on the updated runtime that's already on Flathub stable.
