### ISSUE TITLE
Files always open in new windows

### ISSUE THREAD

**Issue by TiZ-EX1** [flathub/org.geany.Geany#6]
Even though Geany is a tabbed text editor that fancies itself a lightweight IDE, every time I open a file from my file manager, it comes up in an entirely new window. It seems the behavior persists even if you try to do it from the command line.

Geany creates a socket by default within `$XDG_CONFIG_HOME/geany` that it uses to know when it needs to use an existing window. It seems that socket creation is broken in this version; it creates a link to a file in /tmp that does not exist, neither inside nor outside the sandbox. Which tells me it's failing to make the real socket in its own /tmp. It seems to try to do that even if you use the `--socket-file` option, which I can't help but feel defeats the purpose.

If you override it to give it access to /tmp, this starts to work properly. But it's really puzzling that it can't make files in its own sandbox /tmp.

EDIT: I'm on Xubuntu 18.04.2, which ships Flatpak 1.0.8. I updated to 1.4.2 via PPA and the behavior persists.

**Comment by Alexmitter** [comment]
Yes, it seems `flatpak override org.geany.Geany --filesystem=/tmp` does the trick so far. But that is an issue as `--filesystem=host` that is geany's default setting should allow access to /tmp.

**Comment by TiZ-EX1** [comment]
Looks like the /tmp override doesn't even work anymore.

**Comment by TiZ-EX1** [comment]
Sorry to double-post, but the new fix is `flatpak override org.geany.Geany --filesystem=xdg-run/geany:create`.

**Comment by sat3ll** [comment]
> Sorry to double-post, but the new fix is `flatpak override org.geany.Geany --filesystem=xdg-run/geany:create`.

Nice! Do you want to create a PR to apply this fix? Or do you want me to apply the your fix?

**Comment by TingPing** [comment]
That is a bad fix, the config dir is already writable by all processes, so something needs to be tracked down.

**Comment by TiZ-EX1** [comment]
You can take care of it if it would be easier. :)
