### ISSUE TITLE
Spell Check flags every word

### ISSUE THREAD

**Issue by mattmilano** [flathub/org.geany.Geany#93]
With the latest build, on or after 4/26/2024, Spell Check now flags every single word as misspelled. This is confirmed on multiple installs.

![Geany Spell Check](https://github.com/flathub/org.geany.Geany/assets/22775129/89056751-67b7-4976-be53-ba37fa149c7f)

**Comment by TiZ-HugLife** [comment]
I just merged a commit that updates enchant, one of the spellcheck components. Once you get an update for Geany, please let me know if this issue is still present. If so, I can roll back to the enchant 2.6 branch.

**Comment by TiZ-HugLife** [comment]
No response, closing as presumed complete.
